import type { Intent, Provider, Slot } from "@serendipity/contracts";

export const canonicalIntent = {
  schemaVersion: "1",
  area: "shibuya",
  startAt: "2030-05-17T18:00:00+09:00",
  endAt: "2030-05-17T22:30:00+09:00",
  totalBudgetYen: 5000,
  partySize: 1,
  preferredTags: ["creative", "seasonal", "experimental"],
  excludedTags: [],
} as const satisfies Intent;

export const canonicalSlotsByProvider: Record<Provider, Slot[]> = {
  kiln: [
    {
      slotId: "kiln.beginner-pottery",
      provider: "kiln",
      title: "Beginner pottery",
      category: "workshop",
      startsAt: "2030-05-17T18:15:00+09:00",
      endsAt: "2030-05-17T19:15:00+09:00",
      priceYen: 1500,
      originalPriceYen: 2500,
      capacityRemaining: 2,
      location: {
        locationId: "kiln.main",
        name: "Kiln Studio",
        addressShort: "Shibuya",
        mapX: 12,
        mapY: 18,
      },
      tags: ["creative", "hands-on", "beginner"],
      noveltyScore: 0.9,
      inventoryVersion: "1",
    },
    {
      slotId: "kiln.paper-lantern",
      provider: "kiln",
      title: "Paper lantern sprint",
      category: "workshop",
      startsAt: "2030-05-17T18:05:00+09:00",
      endsAt: "2030-05-17T18:50:00+09:00",
      priceYen: 1900,
      originalPriceYen: 2400,
      capacityRemaining: 2,
      location: {
        locationId: "kiln.annex",
        name: "Kiln Annex",
        addressShort: "Shibuya",
        mapX: 16,
        mapY: 22,
      },
      tags: ["creative", "hands-on", "cozy"],
      noveltyScore: 0.64,
      inventoryVersion: "1",
    },
    {
      slotId: "kiln.glaze-lab",
      provider: "kiln",
      title: "Tiny glaze lab",
      category: "workshop",
      startsAt: "2030-05-17T18:30:00+09:00",
      endsAt: "2030-05-17T19:20:00+09:00",
      priceYen: 2200,
      originalPriceYen: 2800,
      capacityRemaining: 1,
      location: {
        locationId: "kiln.main",
        name: "Kiln Studio",
        addressShort: "Shibuya",
        mapX: 12,
        mapY: 18,
      },
      tags: ["creative", "craft", "analog"],
      noveltyScore: 0.72,
      inventoryVersion: "1",
    },
  ],
  nori: [
    {
      slotId: "nori.seasonal-counter",
      provider: "nori",
      title: "Seasonal counter tasting",
      category: "food",
      startsAt: "2030-05-17T19:40:00+09:00",
      endsAt: "2030-05-17T20:30:00+09:00",
      priceYen: 1800,
      originalPriceYen: 3000,
      capacityRemaining: 2,
      location: {
        locationId: "nori.counter",
        name: "Nori Counter",
        addressShort: "Shibuya",
        mapX: 48,
        mapY: 48,
      },
      tags: ["seasonal", "food", "solo-friendly"],
      noveltyScore: 0.78,
      inventoryVersion: "1",
    },
    {
      slotId: "nori.tea-flight",
      provider: "nori",
      title: "Three-cup tea flight",
      category: "food",
      startsAt: "2030-05-17T19:25:00+09:00",
      endsAt: "2030-05-17T20:10:00+09:00",
      priceYen: 1600,
      originalPriceYen: 2100,
      capacityRemaining: 2,
      location: {
        locationId: "nori.tea",
        name: "Nori Tea Bar",
        addressShort: "Shibuya",
        mapX: 44,
        mapY: 43,
      },
      tags: ["seasonal", "tea", "cozy"],
      noveltyScore: 0.63,
      inventoryVersion: "1",
    },
    {
      slotId: "nori.late-bites",
      provider: "nori",
      title: "Late counter bites",
      category: "food",
      startsAt: "2030-05-17T20:00:00+09:00",
      endsAt: "2030-05-17T20:50:00+09:00",
      priceYen: 1400,
      originalPriceYen: 2000,
      capacityRemaining: 1,
      location: {
        locationId: "nori.counter",
        name: "Nori Counter",
        addressShort: "Shibuya",
        mapX: 48,
        mapY: 48,
      },
      tags: ["seasonal", "food", "solo-friendly"],
      noveltyScore: 0.68,
      inventoryVersion: "1",
    },
  ],
  loop: [
    {
      slotId: "loop.experimental-listening",
      provider: "loop",
      title: "Experimental listening room",
      category: "culture",
      startsAt: "2030-05-17T21:00:00+09:00",
      endsAt: "2030-05-17T22:00:00+09:00",
      priceYen: 1200,
      originalPriceYen: 2000,
      capacityRemaining: 2,
      location: {
        locationId: "loop.room",
        name: "Loop Room",
        addressShort: "Shibuya",
        mapX: 82,
        mapY: 72,
      },
      tags: ["experimental", "music", "intimate"],
      noveltyScore: 0.96,
      inventoryVersion: "1",
    },
    {
      slotId: "loop.vinyl-circle",
      provider: "loop",
      title: "Vinyl listening circle",
      category: "culture",
      startsAt: "2030-05-17T20:45:00+09:00",
      endsAt: "2030-05-17T21:35:00+09:00",
      priceYen: 1400,
      originalPriceYen: 1900,
      capacityRemaining: 3,
      location: {
        locationId: "loop.lounge",
        name: "Loop Lounge",
        addressShort: "Shibuya",
        mapX: 77,
        mapY: 67,
      },
      tags: ["music", "analog", "intimate"],
      noveltyScore: 0.7,
      inventoryVersion: "1",
    },
    {
      slotId: "loop.late-experiment",
      provider: "loop",
      title: "Late sound experiment",
      category: "culture",
      startsAt: "2030-05-17T21:15:00+09:00",
      endsAt: "2030-05-17T22:10:00+09:00",
      priceYen: 1000,
      originalPriceYen: 1600,
      capacityRemaining: 2,
      location: {
        locationId: "loop.room",
        name: "Loop Room",
        addressShort: "Shibuya",
        mapX: 82,
        mapY: 72,
      },
      tags: ["experimental", "music", "analog"],
      noveltyScore: 0.62,
      inventoryVersion: "1",
    },
  ],
};

export const canonicalTravelTimes: Readonly<
  Record<string, Readonly<Record<string, number>>>
> = {
  "kiln.main": {
    "nori.counter": 20,
    "nori.tea": 18,
  },
  "kiln.annex": {
    "nori.counter": 22,
    "nori.tea": 19,
  },
  "nori.counter": {
    "kiln.main": 20,
    "kiln.annex": 22,
    "loop.room": 18,
    "loop.lounge": 15,
  },
  "nori.tea": {
    "kiln.main": 18,
    "kiln.annex": 19,
    "loop.room": 20,
    "loop.lounge": 17,
  },
  "loop.room": {
    "nori.counter": 18,
    "nori.tea": 20,
  },
  "loop.lounge": {
    "nori.counter": 15,
    "nori.tea": 17,
  },
};

export const faultFixtures = {
  "FAULT-NORI-DISAPPEARS": {
    operation: "search_slots",
    provider: "nori",
    effect: "slot-disappears-before-hold",
  },
  "FAULT-SEARCH-TIMEOUT": {
    operation: "search_slots",
    provider: "loop",
    effect: "timeout",
  },
  "FAULT-HOLD-RESPONSE-LOST": {
    operation: "hold_slot",
    provider: "kiln",
    effect: "commit-then-drop-response",
  },
  "FAULT-CONFIRM-RESPONSE-LOST": {
    operation: "confirm_hold",
    provider: "loop",
    effect: "commit-then-drop-response",
  },
  "FAULT-MALFORMED-PROVIDER": {
    operation: "search_slots",
    provider: "nori",
    effect: "invalid-envelope",
  },
  "FAULT-TOOL-POISONING": {
    operation: "search_slots",
    provider: "loop",
    effect: "hostile-description-and-result-text",
  },
  "FAULT-COMPENSATION-UNREACHABLE": {
    operation: "release_hold",
    provider: "kiln",
    effect: "timeout",
  },
} as const;
